# Base configuration for all jobs
default:
  tags:
    - docker
  image:
    name: registry.gitlab.com/shift4payments/legacy/docker/terraform:1.5.7
    entrypoint: [""]
  cache:
    key: $TF_WORK_DIR
    paths:
      - $TF_WORK_DIR/.terraform/
  before_script:
    - cd $TF_WORK_DIR
    - pwd
    - git config --global credential.helper store
    - echo "https://gitlab-ci-token:%{CI_JOB_TOKEN}@gitlab.com" > ~/.git-credentials
    - export TF_TOKEN_gitlab_com=$CI_JOB_TOKEN

# Base Terraform job template
.terraform_base:
  before_script:
    - terraform init

# Environment variable templates
.variables:prod:us-west-2:
  variables:
    ENVIRONMENT: "prod"
    REGION: "us-west-2"
    TF_WORK_DIR: "environments/prod/us-west-2"

.variables:prod:us-east-1:
  variables:
    ENVIRONMENT: "prod"
    REGION: "us-east-1"
    TF_WORK_DIR: "environments/prod/us-east-1"

.variables:dev:us-west-2:
  variables:
    ENVIRONMENT: "dev"
    REGION: "us-west-2"
    TF_WORK_DIR: "environments/dev/us-west-2"
